from app.models.application import (
    AdjustmentExecutionAudit,
    ApplicationRequest,
    ApprovalRecord,
)
from app.models.audit import OperationLog
from app.models.base import Base
from app.models.curriculum import (
    AcademicTerm,
    CoursePrerequisite,
    ExperimentCourse,
    ExperimentProject,
    ProjectOrderConstraint,
    TrainingPlan,
    TrainingPlanCourse,
    TrainingPlanProject,
)
from app.models.enrollment import (
    SelectionWindow,
    StudentCourseCompletion,
    StudentProjectRecord,
)
from app.models.identity import (
    Campus,
    Major,
    Student,
    StudentBusyBitmap,
    StudentClass,
    Teacher,
    TeacherBusyBitmap,
    UserAccount,
)
from app.models.notification import Notification
from app.models.resources import (
    EquipmentAsset,
    EquipmentAssetEvent,
    EquipmentType,
    LabEquipmentInventory,
    Laboratory,
    LabProjectCapability,
    ProjectEquipmentRequirement,
    ResourceIssueAsset,
    ResourceIssueObservation,
    ResourceIssueReport,
    TeacherProjectQualification,
)
from app.models.rules import RuleConfig, RuleSet
from app.models.scheduling import (
    CourseTimeAvailability,
    ExperimentSession,
    ProjectDemand,
    ScheduleJob,
    ScheduleVersion,
    TeacherTimetableEntry,
    TeachingTask,
    TeachingTaskCohort,
)
from app.models.teaching_adjustment import (
    AdjustmentRemediationItem,
    AdjustmentRemediationPlan,
    ApplicationApprovalTask,
    EquipmentInventoryMovement,
    ResourceRelocationItem,
    ResourceRelocationPlan,
    ResourceRepairUpdate,
    SessionExecutionOverride,
)

__all__ = [
    "AcademicTerm",
    "AdjustmentExecutionAudit",
    "AdjustmentRemediationItem",
    "AdjustmentRemediationPlan",
    "ApplicationApprovalTask",
    "ApplicationRequest",
    "ApprovalRecord",
    "Base",
    "Campus",
    "CoursePrerequisite",
    "CourseTimeAvailability",
    "EquipmentAsset",
    "EquipmentAssetEvent",
    "EquipmentInventoryMovement",
    "EquipmentType",
    "ExperimentCourse",
    "ExperimentProject",
    "ExperimentSession",
    "LabEquipmentInventory",
    "LabProjectCapability",
    "Laboratory",
    "Major",
    "Notification",
    "OperationLog",
    "ProjectDemand",
    "ProjectEquipmentRequirement",
    "ProjectOrderConstraint",
    "ResourceIssueAsset",
    "ResourceIssueObservation",
    "ResourceIssueReport",
    "ResourceRelocationItem",
    "ResourceRelocationPlan",
    "ResourceRepairUpdate",
    "RuleConfig",
    "RuleSet",
    "ScheduleJob",
    "ScheduleVersion",
    "SelectionWindow",
    "SessionExecutionOverride",
    "Student",
    "StudentBusyBitmap",
    "StudentClass",
    "StudentProjectRecord",
    "Teacher",
    "TeacherBusyBitmap",
    "TeacherProjectQualification",
    "TeacherTimetableEntry",
    "TeachingTask",
    "TeachingTaskCohort",
    "TrainingPlan",
    "TrainingPlanCourse",
    "TrainingPlanProject",
    "UserAccount",
]
