"""add_teacher_busy_bitmap

Revision ID: 05ad2bf43756
Revises: e7a4c9d2b610
Create Date: 2026-07-30 16:48:24.389191
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '05ad2bf43756'
down_revision: str | Sequence[str] | None = 'e7a4c9d2b610'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_availability',
    sa.Column('teacher_id', sa.Uuid(), nullable=False),
    sa.Column('term_id', sa.Uuid(), nullable=False),
    sa.Column('week_start', sa.SmallInteger(), nullable=False),
    sa.Column('week_end', sa.SmallInteger(), nullable=False),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=False),
    sa.Column('start_slot', sa.SmallInteger(), nullable=False),
    sa.Column('end_slot', sa.SmallInteger(), nullable=False),
    sa.Column('availability_type', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("availability_type IN ('AVAILABLE', 'UNAVAILABLE', 'PREFERRED')", name=op.f('ck_teacher_availability_availability_type_allowed')),
    sa.CheckConstraint('day_of_week BETWEEN 1 AND 7', name=op.f('ck_teacher_availability_day_valid')),
    sa.CheckConstraint('end_slot >= start_slot', name=op.f('ck_teacher_availability_slot_range_valid')),
    sa.CheckConstraint('start_slot >= 1', name=op.f('ck_teacher_availability_start_slot_positive')),
    sa.CheckConstraint('week_end >= week_start', name=op.f('ck_teacher_availability_week_range_valid')),
    sa.CheckConstraint('week_start >= 1', name=op.f('ck_teacher_availability_week_start_positive')),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], name=op.f('fk_teacher_availability_teacher_id_teacher'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_id'], ['academic_term.id'], name=op.f('fk_teacher_availability_term_id_academic_term'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teacher_availability'))
    )
    op.create_index('ix_teacher_availability_lookup', 'teacher_availability', ['teacher_id', 'term_id', 'day_of_week'], unique=False)
    op.create_table('teacher_busy_bitmap',
    sa.Column('teacher_id', sa.Uuid(), nullable=False),
    sa.Column('term_id', sa.Uuid(), nullable=False),
    sa.Column('start_week', sa.SmallInteger(), nullable=False),
    sa.Column('end_week', sa.SmallInteger(), nullable=False),
    sa.Column('days_per_week', sa.SmallInteger(), nullable=False),
    sa.Column('slots_per_day', sa.SmallInteger(), nullable=False),
    sa.Column('bitmap', sa.LargeBinary(), nullable=False),
    sa.Column('mapping_version', sa.Integer(), nullable=False),
    sa.Column('source_version', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('days_per_week BETWEEN 1 AND 7', name=op.f('ck_teacher_busy_bitmap_tb_days_valid')),
    sa.CheckConstraint('end_week >= start_week', name=op.f('ck_teacher_busy_bitmap_tb_week_range_valid')),
    sa.CheckConstraint('slots_per_day >= 1', name=op.f('ck_teacher_busy_bitmap_tb_slots_positive')),
    sa.CheckConstraint('start_week >= 1', name=op.f('ck_teacher_busy_bitmap_tb_start_week_positive')),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], name=op.f('fk_teacher_busy_bitmap_teacher_id_teacher'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_id'], ['academic_term.id'], name=op.f('fk_teacher_busy_bitmap_term_id_academic_term'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teacher_busy_bitmap')),
    sa.UniqueConstraint('teacher_id', 'term_id', 'mapping_version', name='teacher_term_mapping')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teacher_busy_bitmap')
    op.drop_index('ix_teacher_availability_lookup', table_name='teacher_availability')
    op.drop_table('teacher_availability')
    # ### end Alembic commands ###
