"""add training plan publisher

Revision ID: 098ffc3a9b59
Revises: 8dbcd826492c
Create Date: 2026-07-28 12:35:04.646386
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '098ffc3a9b59'
down_revision: str | Sequence[str] | None = '8dbcd826492c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_plan', sa.Column('published_by', sa.Uuid(), nullable=True))
    op.create_foreign_key(op.f('fk_training_plan_published_by_user_account'), 'training_plan', 'user_account', ['published_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_training_plan_published_by_user_account'), 'training_plan', type_='foreignkey')
    op.drop_column('training_plan', 'published_by')
    # ### end Alembic commands ###
