"""initial schema

Revision ID: 8dbcd826492c
Revises: 
Create Date: 2026-07-28 12:34:00.779572
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '8dbcd826492c'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_term',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('academic_year', sa.String(length=16), nullable=False),
    sa.Column('semester_no', sa.SmallInteger(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('total_weeks', sa.SmallInteger(), nullable=False),
    sa.Column('days_per_week', sa.SmallInteger(), nullable=False),
    sa.Column('slots_per_day', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT', 'ACTIVE', 'CLOSED')", name=op.f('ck_academic_term_status_allowed')),
    sa.CheckConstraint('days_per_week BETWEEN 1 AND 7', name=op.f('ck_academic_term_days_valid')),
    sa.CheckConstraint('semester_no BETWEEN 1 AND 3', name=op.f('ck_academic_term_semester_valid')),
    sa.CheckConstraint('slots_per_day >= 1', name=op.f('ck_academic_term_slots_positive')),
    sa.CheckConstraint('total_weeks >= 1', name=op.f('ck_academic_term_total_weeks_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_academic_term')),
    sa.UniqueConstraint('academic_year', 'semester_no', name='academic_year_semester'),
    sa.UniqueConstraint('code', name=op.f('uq_academic_term_code'))
    )
    op.create_table('campus',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'INACTIVE')", name=op.f('ck_campus_status_allowed')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campus')),
    sa.UniqueConstraint('code', name=op.f('uq_campus_code'))
    )
    op.create_table('equipment_type',
    sa.Column('equipment_code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'INACTIVE')", name=op.f('ck_equipment_type_status_allowed')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_equipment_type')),
    sa.UniqueConstraint('equipment_code', name=op.f('uq_equipment_type_equipment_code'))
    )
    op.create_table('experiment_course',
    sa.Column('course_code', sa.String(length=32), nullable=False),
    sa.Column('course_name', sa.String(length=100), nullable=False),
    sa.Column('credits', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('default_slots', sa.SmallInteger(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'INACTIVE')", name=op.f('ck_experiment_course_status_allowed')),
    sa.CheckConstraint('credits >= 0', name=op.f('ck_experiment_course_credits_nonnegative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiment_course')),
    sa.UniqueConstraint('course_code', name=op.f('uq_experiment_course_course_code'))
    )
    op.create_table('major',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('degree_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'INACTIVE')", name=op.f('ck_major_status_allowed')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_major')),
    sa.UniqueConstraint('code', name=op.f('uq_major_code')),
    sa.UniqueConstraint('name', name=op.f('uq_major_name'))
    )
    op.create_table('user_account',
    sa.Column('login_name', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('user_type', sa.String(length=20), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'LOCKED', 'DISABLED')", name=op.f('ck_user_account_status_allowed')),
    sa.CheckConstraint("user_type IN ('STUDENT', 'TEACHER', 'ADMIN', 'AUDITOR')", name=op.f('ck_user_account_user_type_allowed')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_account')),
    sa.UniqueConstraint('login_name', name=op.f('uq_user_account_login_name'))
    )
    op.create_index('ix_user_account_type_status', 'user_account', ['user_type', 'status'], unique=False)
    op.create_table('agent_run',
    sa.Column('thread_id', sa.String(length=128), nullable=False),
    sa.Column('graph_name', sa.String(length=100), nullable=False),
    sa.Column('graph_version', sa.String(length=32), nullable=False),
    sa.Column('requester_user_id', sa.Uuid(), nullable=False),
    sa.Column('business_type', sa.String(length=64), nullable=True),
    sa.Column('business_id', sa.Uuid(), nullable=True),
    sa.Column('prompt_versions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('PENDING', 'RUNNING', 'INTERRUPTED', 'SUCCEEDED', 'FAILED', 'CANCELLED')", name=op.f('ck_agent_run_status_allowed')),
    sa.ForeignKeyConstraint(['requester_user_id'], ['user_account.id'], name=op.f('fk_agent_run_requester_user_id_user_account'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_run')),
    sa.UniqueConstraint('thread_id', name=op.f('uq_agent_run_thread_id'))
    )
    op.create_index('ix_agent_run_requester_status', 'agent_run', ['requester_user_id', 'status'], unique=False)
    op.create_table('experiment_project',
    sa.Column('project_code', sa.String(length=32), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('project_name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('required_slots', sa.SmallInteger(), nullable=False),
    sa.Column('default_group_size', sa.SmallInteger(), nullable=False),
    sa.Column('material_note', sa.Text(), nullable=True),
    sa.Column('historical_selection_ratio', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IN ('BASIC', 'MECHANICS', 'ELECTRICITY', 'OPTICS', 'MODERN', 'OTHER')", name=op.f('ck_experiment_project_category_allowed')),
    sa.CheckConstraint("status IN ('ACTIVE', 'INACTIVE')", name=op.f('ck_experiment_project_status_allowed')),
    sa.CheckConstraint('default_group_size >= 1', name=op.f('ck_experiment_project_group_size_positive')),
    sa.CheckConstraint('historical_selection_ratio BETWEEN 0 AND 1', name=op.f('ck_experiment_project_selection_ratio_valid')),
    sa.CheckConstraint('required_slots >= 1', name=op.f('ck_experiment_project_slots_positive')),
    sa.ForeignKeyConstraint(['course_id'], ['experiment_course.id'], name=op.f('fk_experiment_project_course_id_experiment_course'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiment_project')),
    sa.UniqueConstraint('course_id', 'project_name', name='course_project_name'),
    sa.UniqueConstraint('project_code', name=op.f('uq_experiment_project_project_code'))
    )
    op.create_index('ix_experiment_project_course_status', 'experiment_project', ['course_id', 'status'], unique=False)
    op.create_table('notification',
    sa.Column('recipient_user_id', sa.Uuid(), nullable=False),
    sa.Column('notification_type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('business_type', sa.String(length=64), nullable=True),
    sa.Column('business_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("notification_type IN ('SYSTEM', 'SELECTION', 'APPLICATION', 'SCHEDULE', 'RESOURCE')", name=op.f('ck_notification_notification_type_allowed')),
    sa.CheckConstraint("status IN ('PENDING', 'SENT', 'READ', 'FAILED')", name=op.f('ck_notification_status_allowed')),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['user_account.id'], name=op.f('fk_notification_recipient_user_id_user_account'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification'))
    )
    op.create_index('ix_notification_recipient_status', 'notification', ['recipient_user_id', 'status'], unique=False)
    op.create_table('prompt_template',
    sa.Column('agent_code', sa.String(length=64), nullable=False),
    sa.Column('version_no', sa.String(length=32), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('input_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prompt_hash', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('published_by', sa.Uuid(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED')", name=op.f('ck_prompt_template_status_allowed')),
    sa.ForeignKeyConstraint(['published_by'], ['user_account.id'], name=op.f('fk_prompt_template_published_by_user_account'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompt_template')),
    sa.UniqueConstraint('agent_code', 'version_no', name='agent_version')
    )
    op.create_index('ix_prompt_template_agent_status', 'prompt_template', ['agent_code', 'status'], unique=False)
    op.create_table('rule_set',
    sa.Column('rule_set_code', sa.String(length=64), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_by', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED')", name=op.f('ck_rule_set_status_allowed')),
    sa.ForeignKeyConstraint(['published_by'], ['user_account.id'], name=op.f('fk_rule_set_published_by_user_account'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rule_set')),
    sa.UniqueConstraint('rule_set_code', 'version_no', name='code_version')
    )
    op.create_index('uq_rule_set_published', 'rule_set', ['rule_set_code'], unique=True, postgresql_where=sa.text("status = 'PUBLISHED'"))
    op.create_table('selection_window',
    sa.Column('term_id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=True),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('withdraw_end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT', 'OPEN', 'CLOSED')", name=op.f('ck_selection_window_status_allowed')),
    sa.CheckConstraint('end_at > start_at', name=op.f('ck_selection_window_time_range_valid')),
    sa.CheckConstraint('withdraw_end_at IS NULL OR withdraw_end_at >= end_at', name=op.f('ck_selection_window_withdraw_time_valid')),
    sa.ForeignKeyConstraint(['course_id'], ['experiment_course.id'], name=op.f('fk_selection_window_course_id_experiment_course'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_id'], ['academic_term.id'], name=op.f('fk_selection_window_term_id_academic_term'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_selection_window'))
    )
    op.create_index('ix_selection_window_term_status', 'selection_window', ['term_id', 'status'], unique=False)
    op.create_table('student_class',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('major_id', sa.Uuid(), nullable=False),
    sa.Column('enrollment_year', sa.SmallInteger(), nullable=False),
    sa.Column('campus_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'GRADUATED', 'INACTIVE')", name=op.f('ck_student_class_status_allowed')),
    sa.ForeignKeyConstraint(['campus_id'], ['campus.id'], name=op.f('fk_student_class_campus_id_campus'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['major_id'], ['major.id'], name=op.f('fk_student_class_major_id_major'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_class')),
    sa.UniqueConstraint('major_id', 'enrollment_year', 'code', name='major_year_code')
    )
    op.create_index('ix_student_class_major_year', 'student_class', ['major_id', 'enrollment_year'], unique=False)
    op.create_table('teacher',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('employee_no', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('campus_id', sa.Uuid(), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'LEAVE', 'INACTIVE')", name=op.f('ck_teacher_status_allowed')),
    sa.ForeignKeyConstraint(['campus_id'], ['campus.id'], name=op.f('fk_teacher_campus_id_campus'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_teacher_user_id_user_account'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teacher')),
    sa.UniqueConstraint('employee_no', name=op.f('uq_teacher_employee_no')),
    sa.UniqueConstraint('user_id', name=op.f('uq_teacher_user_id'))
    )
    op.create_index('ix_teacher_campus_status', 'teacher', ['campus_id', 'status'], unique=False)
    op.create_table('teaching_task',
    sa.Column('task_code', sa.String(length=64), nullable=False),
    sa.Column('term_id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('planned_student_count', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.SmallInteger(), nullable=False),
    sa.Column('week_end', sa.SmallInteger(), nullable=False),
    sa.Column('capacity_buffer_ratio', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT', 'READY', 'SCHEDULING', 'PUBLISHED', 'CLOSED')", name=op.f('ck_teaching_task_status_allowed')),
    sa.CheckConstraint('capacity_buffer_ratio >= 1', name=op.f('ck_teaching_task_buffer_ratio_valid')),
    sa.CheckConstraint('planned_student_count >= 0', name=op.f('ck_teaching_task_student_count_valid')),
    sa.CheckConstraint('week_end >= week_start', name=op.f('ck_teaching_task_week_range_valid')),
    sa.CheckConstraint('week_start >= 1', name=op.f('ck_teaching_task_week_start_positive')),
    sa.ForeignKeyConstraint(['course_id'], ['experiment_course.id'], name=op.f('fk_teaching_task_course_id_experiment_course'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['term_id'], ['academic_term.id'], name=op.f('fk_teaching_task_term_id_academic_term'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teaching_task')),
    sa.UniqueConstraint('task_code', name=op.f('uq_teaching_task_task_code'))
    )
    op.create_index('ix_teaching_task_term_status', 'teaching_task', ['term_id', 'status'], unique=False)
    op.create_table('training_plan',
    sa.Column('plan_code', sa.String(length=64), nullable=False),
    sa.Column('major_id', sa.Uuid(), nullable=False),
    sa.Column('enrollment_year', sa.SmallInteger(), nullable=False),
    sa.Column('version_no', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED')", name=op.f('ck_training_plan_status_allowed')),
    sa.ForeignKeyConstraint(['major_id'], ['major.id'], name=op.f('fk_training_plan_major_id_major'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_training_plan')),
    sa.UniqueConstraint('major_id', 'enrollment_year', 'version_no', name='major_year_version'),
    sa.UniqueConstraint('plan_code', name=op.f('uq_training_plan_plan_code'))
    )
    op.create_index('uq_training_plan_published', 'training_plan', ['major_id', 'enrollment_year'], unique=True, postgresql_where=sa.text("status = 'PUBLISHED'"))
    op.create_table('agent_feedback',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('feedback_type', sa.String(length=64), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name=op.f('ck_agent_feedback_rating_valid')),
    sa.ForeignKeyConstraint(['run_id'], ['agent_run.id'], name=op.f('fk_agent_feedback_run_id_agent_run'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_agent_feedback_user_id_user_account'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_feedback'))
    )
    op.create_index('ix_agent_feedback_run', 'agent_feedback', ['run_id'], unique=False)
    op.create_table('agent_step_log',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('node_name', sa.String(length=100), nullable=False),
    sa.Column('agent_code', sa.String(length=64), nullable=True),
    sa.Column('input_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tool_calls', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('token_usage', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'INTERRUPTED', 'SKIPPED')", name=op.f('ck_agent_step_log_status_allowed')),
    sa.ForeignKeyConstraint(['run_id'], ['agent_run.id'], name=op.f('fk_agent_step_log_run_id_agent_run'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_step_log'))
    )
    op.create_index('ix_agent_step_log_run_time', 'agent_step_log', ['run_id', 'created_at'], unique=False)
    op.create_table('laboratory',
    sa.Column('lab_code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('campus_id', sa.Uuid(), nullable=False),
    sa.Column('room_type', sa.String(length=64), nullable=True),
    sa.Column('safety_capacity', sa.Integer(), nullable=False),
    sa.Column('manager_teacher_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'LIMITED', 'INACTIVE')", name=op.f('ck_laboratory_status_allowed')),
    sa.CheckConstraint('safety_capacity >= 1', name=op.f('ck_laboratory_capacity_positive')),
    sa.ForeignKeyConstraint(['campus_id'], ['campus.id'], name=op.f('fk_laboratory_campus_id_campus'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['manager_teacher_id'], ['teacher.id'], name=op.f('fk_laboratory_manager_teacher_id_teacher'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_laboratory')),
    sa.UniqueConstraint('lab_code', name=op.f('uq_laboratory_lab_code'))
    )
    op.create_index('ix_laboratory_campus_status', 'laboratory', ['campus_id', 'status'], unique=False)
    op.create_table('operation_log',
    sa.Column('operator_user_id', sa.Uuid(), nullable=True),
    sa.Column('operation_type', sa.String(length=64), nullable=False),
    sa.Column('object_type', sa.String(length=64), nullable=False),
    sa.Column('object_id', sa.Uuid(), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('before_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('after_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rule_set_id', sa.Uuid(), nullable=True),
    sa.Column('result', sa.String(length=32), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operator_user_id'], ['user_account.id'], name=op.f('fk_operation_log_operator_user_id_user_account'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rule_set_id'], ['rule_set.id'], name=op.f('fk_operation_log_rule_set_id_rule_set'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operation_log'))
    )
    op.create_index('ix_operation_log_object', 'operation_log', ['object_type', 'object_id'], unique=False)
    op.create_index('ix_operation_log_operator_time', 'operation_log', ['operator_user_id', 'created_at'], unique=False)
    op.create_table('project_demand',
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('requirement_type', sa.String(length=20), nullable=False),
    sa.Column('base_demand', sa.Integer(), nullable=False),
    sa.Column('prediction_ratio', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('buffer_ratio', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('required_capacity', sa.Integer(), nullable=False),
    sa.Column('required_session_count', sa.Integer(), nullable=False),
    sa.Column('calculation_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("requirement_type IN ('REQUIRED', 'OPTIONAL')", name=op.f('ck_project_demand_requirement_type_allowed')),
    sa.CheckConstraint('base_demand >= 0', name=op.f('ck_project_demand_base_demand_nonnegative')),
    sa.CheckConstraint('buffer_ratio >= 1', name=op.f('ck_project_demand_buffer_ratio_valid')),
    sa.CheckConstraint('prediction_ratio BETWEEN 0 AND 1', name=op.f('ck_project_demand_prediction_ratio_valid')),
    sa.CheckConstraint('required_capacity >= 0', name=op.f('ck_project_demand_required_capacity_nonnegative')),
    sa.CheckConstraint('required_session_count >= 0', name=op.f('ck_project_demand_required_session_count_nonnegative')),
    sa.ForeignKeyConstraint(['project_id'], ['experiment_project.id'], name=op.f('fk_project_demand_project_id_experiment_project'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_id'], ['teaching_task.id'], name=op.f('fk_project_demand_task_id_teaching_task'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_demand')),
    sa.UniqueConstraint('task_id', 'project_id', name='task_project')
    )
    op.create_table('project_equipment_requirement',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('equipment_type_id', sa.Uuid(), nullable=False),
    sa.Column('units_per_group', sa.SmallInteger(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('units_per_group >= 0', name=op.f('ck_project_equipment_requirement_units_nonnegative')),
    sa.ForeignKeyConstraint(['equipment_type_id'], ['equipment_type.id'], name=op.f('fk_project_equipment_requirement_equipment_type_id_equipment_type'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['experiment_project.id'], name=op.f('fk_project_equipment_requirement_project_id_experiment_project'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_equipment_requirement')),
    sa.UniqueConstraint('project_id', 'equipment_type_id', name='project_equipment')
    )
    op.create_table('rule_config',
    sa.Column('rule_set_id', sa.Uuid(), nullable=False),
    sa.Column('rule_code', sa.String(length=64), nullable=False),
    sa.Column('rule_name', sa.String(length=150), nullable=False),
    sa.Column('rule_type', sa.String(length=20), nullable=False),
    sa.Column('scope_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('condition_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('action_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('weight', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("rule_type IN ('HARD', 'SOFT', 'RUNTIME', 'APPROVAL')", name=op.f('ck_rule_config_rule_type_allowed')),
    sa.CheckConstraint('priority >= 0', name=op.f('ck_rule_config_priority_nonnegative')),
    sa.CheckConstraint('weight >= 0', name=op.f('ck_rule_config_weight_nonnegative')),
    sa.ForeignKeyConstraint(['rule_set_id'], ['rule_set.id'], name=op.f('fk_rule_config_rule_set_id_rule_set'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rule_config')),
    sa.UniqueConstraint('rule_set_id', 'rule_code', name='rule_set_code')
    )
    op.create_index('ix_rule_config_type_enabled', 'rule_config', ['rule_type', 'enabled'], unique=False)
    op.create_table('schedule_job',
    sa.Column('term_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('job_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rule_set_id', sa.Uuid(), nullable=False),
    sa.Column('input_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("job_type IN ('INITIAL', 'LOCAL_ADJUSTMENT', 'VALIDATION')", name=op.f('ck_schedule_job_job_type_allowed')),
    sa.CheckConstraint("status IN ('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED', 'TIMEOUT')", name=op.f('ck_schedule_job_status_allowed')),
    sa.CheckConstraint('progress BETWEEN 0 AND 100', name=op.f('ck_schedule_job_progress_valid')),
    sa.ForeignKeyConstraint(['rule_set_id'], ['rule_set.id'], name=op.f('fk_schedule_job_rule_set_id_rule_set'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_id'], ['teaching_task.id'], name=op.f('fk_schedule_job_task_id_teaching_task'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['term_id'], ['academic_term.id'], name=op.f('fk_schedule_job_term_id_academic_term'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedule_job'))
    )
    op.create_index('ix_schedule_job_term_status', 'schedule_job', ['term_id', 'status'], unique=False)
    op.create_table('student',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('student_no', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=16), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('enrollment_year', sa.SmallInteger(), nullable=False),
    sa.Column('major_id', sa.Uuid(), nullable=False),
    sa.Column('class_id', sa.Uuid(), nullable=False),
    sa.Column('campus_id', sa.Uuid(), nullable=False),
    sa.Column('academic_status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("academic_status IN ('ACTIVE', 'SUSPENDED', 'GRADUATED', 'WITHDRAWN')", name=op.f('ck_student_academic_status_allowed')),
    sa.ForeignKeyConstraint(['campus_id'], ['campus.id'], name=op.f('fk_student_campus_id_campus'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['class_id'], ['student_class.id'], name=op.f('fk_student_class_id_student_class'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['major_id'], ['major.id'], name=op.f('fk_student_major_id_major'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_student_user_id_user_account'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student')),
    sa.UniqueConstraint('student_no', name=op.f('uq_student_student_no')),
    sa.UniqueConstraint('user_id', name=op.f('uq_student_user_id'))
    )
    op.create_index('ix_student_class', 'student', ['class_id'], unique=False)
    op.create_index('ix_student_major_year', 'student', ['major_id', 'enrollment_year'], unique=False)
    op.create_table('teacher_availability',
    sa.Column('teacher_id', sa.Uuid(), nullable=False),
    sa.Column('term_id', sa.Uuid(), nullable=False),
    sa.Column('week_start', sa.SmallInteger(), nullable=False),
    sa.Column('week_end', sa.SmallInteger(), nullable=False),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=False),
    sa.Column('start_slot', sa.SmallInteger(), nullable=False),
    sa.Column('end_slot', sa.SmallInteger(), nullable=False),
    sa.Column('availability_type', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("availability_type IN ('AVAILABLE', 'UNAVAILABLE', 'PREFERRED')", name=op.f('ck_teacher_availability_availability_type_allowed')),
    sa.CheckConstraint('day_of_week BETWEEN 1 AND 7', name=op.f('ck_teacher_availability_day_valid')),
    sa.CheckConstraint('end_slot >= start_slot', name=op.f('ck_teacher_availability_slot_range_valid')),
    sa.CheckConstraint('start_slot >= 1', name=op.f('ck_teacher_availability_start_slot_positive')),
    sa.CheckConstraint('week_end >= week_start', name=op.f('ck_teacher_availability_week_range_valid')),
    sa.CheckConstraint('week_start >= 1', name=op.f('ck_teacher_availability_week_start_positive')),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], name=op.f('fk_teacher_availability_teacher_id_teacher'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_id'], ['academic_term.id'], name=op.f('fk_teacher_availability_term_id_academic_term'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teacher_availability'))
    )
    op.create_index('ix_teacher_availability_lookup', 'teacher_availability', ['teacher_id', 'term_id', 'day_of_week'], unique=False)
    op.create_table('teacher_project_qualification',
    sa.Column('teacher_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'EXPIRED', 'SUSPENDED')", name=op.f('ck_teacher_project_qualification_status_allowed')),
    sa.ForeignKeyConstraint(['project_id'], ['experiment_project.id'], name=op.f('fk_teacher_project_qualification_project_id_experiment_project'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], name=op.f('fk_teacher_project_qualification_teacher_id_teacher'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teacher_project_qualification')),
    sa.UniqueConstraint('teacher_id', 'project_id', name='teacher_project')
    )
    op.create_table('teaching_task_cohort',
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('major_id', sa.Uuid(), nullable=False),
    sa.Column('enrollment_year', sa.SmallInteger(), nullable=False),
    sa.Column('class_id', sa.Uuid(), nullable=True),
    sa.Column('student_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('student_count >= 0', name=op.f('ck_teaching_task_cohort_student_count_nonnegative')),
    sa.ForeignKeyConstraint(['class_id'], ['student_class.id'], name=op.f('fk_teaching_task_cohort_class_id_student_class'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['major_id'], ['major.id'], name=op.f('fk_teaching_task_cohort_major_id_major'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_id'], ['teaching_task.id'], name=op.f('fk_teaching_task_cohort_task_id_teaching_task'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teaching_task_cohort')),
    sa.UniqueConstraint('task_id', 'major_id', 'enrollment_year', 'class_id', name='task_cohort')
    )
    op.create_table('training_plan_course',
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('course_nature', sa.String(length=20), nullable=False),
    sa.Column('study_year', sa.SmallInteger(), nullable=False),
    sa.Column('semester_no', sa.SmallInteger(), nullable=False),
    sa.Column('required_project_count', sa.SmallInteger(), nullable=False),
    sa.Column('optional_project_min_count', sa.SmallInteger(), nullable=False),
    sa.Column('order_rule_text', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("course_nature IN ('REQUIRED', 'ELECTIVE')", name=op.f('ck_training_plan_course_course_nature_allowed')),
    sa.CheckConstraint('optional_project_min_count >= 0', name=op.f('ck_training_plan_course_optional_count_nonnegative')),
    sa.CheckConstraint('required_project_count >= 0', name=op.f('ck_training_plan_course_required_count_nonnegative')),
    sa.CheckConstraint('semester_no BETWEEN 1 AND 3', name=op.f('ck_training_plan_course_semester_valid')),
    sa.CheckConstraint('study_year BETWEEN 1 AND 6', name=op.f('ck_training_plan_course_study_year_valid')),
    sa.ForeignKeyConstraint(['course_id'], ['experiment_course.id'], name=op.f('fk_training_plan_course_course_id_experiment_course'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['plan_id'], ['training_plan.id'], name=op.f('fk_training_plan_course_plan_id_training_plan'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_training_plan_course')),
    sa.UniqueConstraint('plan_id', 'course_id', name='plan_course')
    )
    op.create_table('course_prerequisite',
    sa.Column('plan_course_id', sa.Uuid(), nullable=False),
    sa.Column('prerequisite_course_id', sa.Uuid(), nullable=False),
    sa.Column('requirement_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("requirement_type IN ('MUST_COMPLETE', 'MUST_ENROLL', 'ADVISORY')", name=op.f('ck_course_prerequisite_requirement_type_allowed')),
    sa.ForeignKeyConstraint(['plan_course_id'], ['training_plan_course.id'], name=op.f('fk_course_prerequisite_plan_course_id_training_plan_course'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prerequisite_course_id'], ['experiment_course.id'], name=op.f('fk_course_prerequisite_prerequisite_course_id_experiment_course'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_prerequisite')),
    sa.UniqueConstraint('plan_course_id', 'prerequisite_course_id', name='plan_course_prerequisite')
    )
    op.create_table('lab_equipment_inventory',
    sa.Column('laboratory_id', sa.Uuid(), nullable=False),
    sa.Column('equipment_type_id', sa.Uuid(), nullable=False),
    sa.Column('total_quantity', sa.Integer(), nullable=False),
    sa.Column('usable_quantity', sa.Integer(), nullable=False),
    sa.Column('disabled_quantity', sa.Integer(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('disabled_quantity >= 0', name=op.f('ck_lab_equipment_inventory_disabled_nonnegative')),
    sa.CheckConstraint('total_quantity >= 0', name=op.f('ck_lab_equipment_inventory_total_nonnegative')),
    sa.CheckConstraint('usable_quantity + disabled_quantity <= total_quantity', name=op.f('ck_lab_equipment_inventory_quantity_sum_valid')),
    sa.CheckConstraint('usable_quantity >= 0', name=op.f('ck_lab_equipment_inventory_usable_nonnegative')),
    sa.ForeignKeyConstraint(['equipment_type_id'], ['equipment_type.id'], name=op.f('fk_lab_equipment_inventory_equipment_type_id_equipment_type'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['laboratory_id'], ['laboratory.id'], name=op.f('fk_lab_equipment_inventory_laboratory_id_laboratory'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lab_equipment_inventory')),
    sa.UniqueConstraint('laboratory_id', 'equipment_type_id', name='lab_equipment')
    )
    op.create_table('lab_project_capability',
    sa.Column('laboratory_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('effective_capacity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'SUSPENDED', 'INACTIVE')", name=op.f('ck_lab_project_capability_status_allowed')),
    sa.CheckConstraint('effective_capacity >= 1', name=op.f('ck_lab_project_capability_capacity_positive')),
    sa.ForeignKeyConstraint(['laboratory_id'], ['laboratory.id'], name=op.f('fk_lab_project_capability_laboratory_id_laboratory'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['experiment_project.id'], name=op.f('fk_lab_project_capability_project_id_experiment_project'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lab_project_capability')),
    sa.UniqueConstraint('laboratory_id', 'project_id', name='lab_project')
    )
    op.create_table('project_order_constraint',
    sa.Column('plan_course_id', sa.Uuid(), nullable=False),
    sa.Column('before_project_id', sa.Uuid(), nullable=False),
    sa.Column('after_project_id', sa.Uuid(), nullable=False),
    sa.Column('allow_override', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('before_project_id <> after_project_id', name=op.f('ck_project_order_constraint_different_projects')),
    sa.ForeignKeyConstraint(['after_project_id'], ['experiment_project.id'], name=op.f('fk_project_order_constraint_after_project_id_experiment_project'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['before_project_id'], ['experiment_project.id'], name=op.f('fk_project_order_constraint_before_project_id_experiment_project'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['plan_course_id'], ['training_plan_course.id'], name=op.f('fk_project_order_constraint_plan_course_id_training_plan_course'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_order_constraint')),
    sa.UniqueConstraint('plan_course_id', 'before_project_id', 'after_project_id', name='project_order')
    )
    op.create_table('resource_issue_report',
    sa.Column('report_no', sa.String(length=64), nullable=False),
    sa.Column('reporter_teacher_id', sa.Uuid(), nullable=False),
    sa.Column('issue_type', sa.String(length=32), nullable=False),
    sa.Column('laboratory_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('equipment_type_id', sa.Uuid(), nullable=True),
    sa.Column('impact_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('impact_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("issue_type IN ('EQUIPMENT_FAILURE', 'MATERIAL_SHORTAGE', 'LAB_UNAVAILABLE', 'ENVIRONMENT', 'OTHER')", name=op.f('ck_resource_issue_report_issue_type_allowed')),
    sa.CheckConstraint("severity IN ('LOW', 'NORMAL', 'HIGH', 'CRITICAL')", name=op.f('ck_resource_issue_report_severity_allowed')),
    sa.CheckConstraint("status IN ('REPORTED', 'PROCESSING', 'RESOLVED', 'CLOSED')", name=op.f('ck_resource_issue_report_status_allowed')),
    sa.CheckConstraint('impact_end > impact_start', name=op.f('ck_resource_issue_report_impact_range_valid')),
    sa.ForeignKeyConstraint(['equipment_type_id'], ['equipment_type.id'], name=op.f('fk_resource_issue_report_equipment_type_id_equipment_type'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['laboratory_id'], ['laboratory.id'], name=op.f('fk_resource_issue_report_laboratory_id_laboratory'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['experiment_project.id'], name=op.f('fk_resource_issue_report_project_id_experiment_project'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reporter_teacher_id'], ['teacher.id'], name=op.f('fk_resource_issue_report_reporter_teacher_id_teacher'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resource_issue_report')),
    sa.UniqueConstraint('report_no', name=op.f('uq_resource_issue_report_report_no'))
    )
    op.create_index('ix_resource_issue_time', 'resource_issue_report', ['laboratory_id', 'impact_start', 'impact_end'], unique=False)
    op.create_table('schedule_version',
    sa.Column('term_id', sa.Uuid(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('parent_version_id', sa.Uuid(), nullable=True),
    sa.Column('source_job_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('hard_constraint_passed', sa.Boolean(), nullable=False),
    sa.Column('soft_score', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('score_details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('optimization_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rule_set_id', sa.Uuid(), nullable=False),
    sa.Column('published_by', sa.Uuid(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT', 'CANDIDATE', 'PUBLISHED', 'ARCHIVED')", name=op.f('ck_schedule_version_status_allowed')),
    sa.ForeignKeyConstraint(['parent_version_id'], ['schedule_version.id'], name=op.f('fk_schedule_version_parent_version_id_schedule_version'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['published_by'], ['user_account.id'], name=op.f('fk_schedule_version_published_by_user_account'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rule_set_id'], ['rule_set.id'], name=op.f('fk_schedule_version_rule_set_id_rule_set'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_job_id'], ['schedule_job.id'], name=op.f('fk_schedule_version_source_job_id_schedule_job'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['term_id'], ['academic_term.id'], name=op.f('fk_schedule_version_term_id_academic_term'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedule_version')),
    sa.UniqueConstraint('term_id', 'version_no', name='term_version')
    )
    op.create_index('uq_schedule_version_published', 'schedule_version', ['term_id'], unique=True, postgresql_where=sa.text("status = 'PUBLISHED'"))
    op.create_table('student_busy_bitmap',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('term_id', sa.Uuid(), nullable=False),
    sa.Column('start_week', sa.SmallInteger(), nullable=False),
    sa.Column('end_week', sa.SmallInteger(), nullable=False),
    sa.Column('days_per_week', sa.SmallInteger(), nullable=False),
    sa.Column('slots_per_day', sa.SmallInteger(), nullable=False),
    sa.Column('bitmap', sa.LargeBinary(), nullable=False),
    sa.Column('mapping_version', sa.Integer(), nullable=False),
    sa.Column('source_version', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('days_per_week BETWEEN 1 AND 7', name=op.f('ck_student_busy_bitmap_days_valid')),
    sa.CheckConstraint('end_week >= start_week', name=op.f('ck_student_busy_bitmap_week_range_valid')),
    sa.CheckConstraint('slots_per_day >= 1', name=op.f('ck_student_busy_bitmap_slots_positive')),
    sa.CheckConstraint('start_week >= 1', name=op.f('ck_student_busy_bitmap_start_week_positive')),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_student_busy_bitmap_student_id_student'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_id'], ['academic_term.id'], name=op.f('fk_student_busy_bitmap_term_id_academic_term'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_busy_bitmap')),
    sa.UniqueConstraint('student_id', 'term_id', 'mapping_version', name='student_term_mapping')
    )
    op.create_table('training_plan_project',
    sa.Column('plan_course_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('requirement_type', sa.String(length=20), nullable=False),
    sa.Column('display_order', sa.SmallInteger(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("requirement_type IN ('REQUIRED', 'OPTIONAL')", name=op.f('ck_training_plan_project_requirement_type_allowed')),
    sa.ForeignKeyConstraint(['plan_course_id'], ['training_plan_course.id'], name=op.f('fk_training_plan_project_plan_course_id_training_plan_course'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['experiment_project.id'], name=op.f('fk_training_plan_project_project_id_experiment_project'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_training_plan_project')),
    sa.UniqueConstraint('plan_course_id', 'project_id', name='plan_course_project')
    )
    op.create_table('experiment_session',
    sa.Column('schedule_version_id', sa.Uuid(), nullable=False),
    sa.Column('session_code', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('week_no', sa.SmallInteger(), nullable=False),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=False),
    sa.Column('start_slot', sa.SmallInteger(), nullable=False),
    sa.Column('end_slot', sa.SmallInteger(), nullable=False),
    sa.Column('teacher_id', sa.Uuid(), nullable=False),
    sa.Column('laboratory_id', sa.Uuid(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('selected_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT', 'OPEN', 'FULL', 'SUSPENDED', 'CANCELLED', 'COMPLETED')", name=op.f('ck_experiment_session_status_allowed')),
    sa.CheckConstraint('capacity >= 1', name=op.f('ck_experiment_session_capacity_positive')),
    sa.CheckConstraint('day_of_week BETWEEN 1 AND 7', name=op.f('ck_experiment_session_day_valid')),
    sa.CheckConstraint('end_slot >= start_slot', name=op.f('ck_experiment_session_slot_range_valid')),
    sa.CheckConstraint('selected_count <= capacity', name=op.f('ck_experiment_session_selected_within_capacity')),
    sa.CheckConstraint('selected_count >= 0', name=op.f('ck_experiment_session_selected_nonnegative')),
    sa.CheckConstraint('start_slot >= 1', name=op.f('ck_experiment_session_start_slot_positive')),
    sa.CheckConstraint('week_no >= 1', name=op.f('ck_experiment_session_week_positive')),
    sa.ForeignKeyConstraint(['laboratory_id'], ['laboratory.id'], name=op.f('fk_experiment_session_laboratory_id_laboratory'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['experiment_project.id'], name=op.f('fk_experiment_session_project_id_experiment_project'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['schedule_version_id'], ['schedule_version.id'], name=op.f('fk_experiment_session_schedule_version_id_schedule_version'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['teaching_task.id'], name=op.f('fk_experiment_session_task_id_teaching_task'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], name=op.f('fk_experiment_session_teacher_id_teacher'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiment_session')),
    sa.UniqueConstraint('schedule_version_id', 'session_code', name='version_session_code')
    )
    op.create_index('ix_experiment_session_project_status', 'experiment_session', ['project_id', 'status'], unique=False)
    op.create_index('ix_experiment_session_time', 'experiment_session', ['schedule_version_id', 'week_no', 'day_of_week', 'start_slot'], unique=False)
    op.create_table('application_request',
    sa.Column('request_no', sa.String(length=64), nullable=False),
    sa.Column('request_type', sa.String(length=32), nullable=False),
    sa.Column('applicant_user_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=True),
    sa.Column('teacher_id', sa.Uuid(), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('target_project_id', sa.Uuid(), nullable=True),
    sa.Column('original_session_id', sa.Uuid(), nullable=True),
    sa.Column('target_session_id', sa.Uuid(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('validation_result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rule_set_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("request_type IN ('RESCHEDULE', 'MAKEUP', 'PROJECT_CHANGE', 'TEACHER_ADJUSTMENT', 'LAB_CHANGE', 'RESOURCE_ADJUSTMENT')", name=op.f('ck_application_request_request_type_allowed')),
    sa.CheckConstraint("status IN ('DRAFT', 'SUBMITTED', 'VALIDATING', 'PENDING_REVIEW', 'APPROVED', 'REJECTED', 'EXECUTED', 'FAILED', 'CANCELLED')", name=op.f('ck_application_request_status_allowed')),
    sa.ForeignKeyConstraint(['applicant_user_id'], ['user_account.id'], name=op.f('fk_application_request_applicant_user_id_user_account'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['original_session_id'], ['experiment_session.id'], name=op.f('fk_application_request_original_session_id_experiment_session'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['experiment_project.id'], name=op.f('fk_application_request_project_id_experiment_project'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rule_set_id'], ['rule_set.id'], name=op.f('fk_application_request_rule_set_id_rule_set'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_application_request_student_id_student'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_project_id'], ['experiment_project.id'], name=op.f('fk_application_request_target_project_id_experiment_project'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_session_id'], ['experiment_session.id'], name=op.f('fk_application_request_target_session_id_experiment_session'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], name=op.f('fk_application_request_teacher_id_teacher'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_application_request')),
    sa.UniqueConstraint('request_no', name=op.f('uq_application_request_request_no'))
    )
    op.create_index('ix_application_request_applicant_status', 'application_request', ['applicant_user_id', 'status'], unique=False)
    op.create_index('ix_application_request_type_status', 'application_request', ['request_type', 'status'], unique=False)
    op.create_table('student_project_record',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('term_id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('requirement_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('selected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('withdrawn_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('absence_reason', sa.Text(), nullable=True),
    sa.Column('report_status', sa.String(length=20), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("report_status IN ('NOT_REQUIRED', 'PENDING', 'SUBMITTED', 'PASSED', 'REJECTED')", name=op.f('ck_student_project_record_report_status_allowed')),
    sa.CheckConstraint("requirement_type IN ('REQUIRED', 'OPTIONAL')", name=op.f('ck_student_project_record_requirement_type_allowed')),
    sa.CheckConstraint("status IN ('AVAILABLE', 'SELECTED', 'COMPLETED', 'ABSENT', 'WITHDRAWN', 'MAKEUP_PENDING')", name=op.f('ck_student_project_record_status_allowed')),
    sa.ForeignKeyConstraint(['course_id'], ['experiment_course.id'], name=op.f('fk_student_project_record_course_id_experiment_course'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['experiment_project.id'], name=op.f('fk_student_project_record_project_id_experiment_project'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['experiment_session.id'], name=op.f('fk_student_project_record_session_id_experiment_session'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_student_project_record_student_id_student'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_id'], ['academic_term.id'], name=op.f('fk_student_project_record_term_id_academic_term'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_project_record'))
    )
    op.create_index('ix_student_project_record_session_status', 'student_project_record', ['session_id', 'status'], unique=False)
    op.create_index('ix_student_project_record_student_term', 'student_project_record', ['student_id', 'term_id'], unique=False)
    op.create_index('uq_student_project_active', 'student_project_record', ['student_id', 'term_id', 'project_id'], unique=True, postgresql_where=sa.text("status IN ('SELECTED', 'COMPLETED', 'ABSENT', 'MAKEUP_PENDING')"))
    op.create_table('approval_record',
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('approval_type', sa.String(length=20), nullable=False),
    sa.Column('approver_user_id', sa.Uuid(), nullable=True),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('matched_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("approval_type IN ('AUTO', 'MANUAL')", name=op.f('ck_approval_record_approval_type_allowed')),
    sa.CheckConstraint("decision IN ('APPROVED', 'REJECTED', 'TRANSFERRED')", name=op.f('ck_approval_record_decision_allowed')),
    sa.ForeignKeyConstraint(['application_id'], ['application_request.id'], name=op.f('fk_approval_record_application_id_application_request'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['approver_user_id'], ['user_account.id'], name=op.f('fk_approval_record_approver_user_id_user_account'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_record'))
    )
    op.create_index('ix_approval_record_application', 'approval_record', ['application_id', 'decided_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_approval_record_application', table_name='approval_record')
    op.drop_table('approval_record')
    op.drop_index('uq_student_project_active', table_name='student_project_record', postgresql_where=sa.text("status IN ('SELECTED', 'COMPLETED', 'ABSENT', 'MAKEUP_PENDING')"))
    op.drop_index('ix_student_project_record_student_term', table_name='student_project_record')
    op.drop_index('ix_student_project_record_session_status', table_name='student_project_record')
    op.drop_table('student_project_record')
    op.drop_index('ix_application_request_type_status', table_name='application_request')
    op.drop_index('ix_application_request_applicant_status', table_name='application_request')
    op.drop_table('application_request')
    op.drop_index('ix_experiment_session_time', table_name='experiment_session')
    op.drop_index('ix_experiment_session_project_status', table_name='experiment_session')
    op.drop_table('experiment_session')
    op.drop_table('training_plan_project')
    op.drop_table('student_busy_bitmap')
    op.drop_index('uq_schedule_version_published', table_name='schedule_version', postgresql_where=sa.text("status = 'PUBLISHED'"))
    op.drop_table('schedule_version')
    op.drop_index('ix_resource_issue_time', table_name='resource_issue_report')
    op.drop_table('resource_issue_report')
    op.drop_table('project_order_constraint')
    op.drop_table('lab_project_capability')
    op.drop_table('lab_equipment_inventory')
    op.drop_table('course_prerequisite')
    op.drop_table('training_plan_course')
    op.drop_table('teaching_task_cohort')
    op.drop_table('teacher_project_qualification')
    op.drop_index('ix_teacher_availability_lookup', table_name='teacher_availability')
    op.drop_table('teacher_availability')
    op.drop_index('ix_student_major_year', table_name='student')
    op.drop_index('ix_student_class', table_name='student')
    op.drop_table('student')
    op.drop_index('ix_schedule_job_term_status', table_name='schedule_job')
    op.drop_table('schedule_job')
    op.drop_index('ix_rule_config_type_enabled', table_name='rule_config')
    op.drop_table('rule_config')
    op.drop_table('project_equipment_requirement')
    op.drop_table('project_demand')
    op.drop_index('ix_operation_log_operator_time', table_name='operation_log')
    op.drop_index('ix_operation_log_object', table_name='operation_log')
    op.drop_table('operation_log')
    op.drop_index('ix_laboratory_campus_status', table_name='laboratory')
    op.drop_table('laboratory')
    op.drop_index('ix_agent_step_log_run_time', table_name='agent_step_log')
    op.drop_table('agent_step_log')
    op.drop_index('ix_agent_feedback_run', table_name='agent_feedback')
    op.drop_table('agent_feedback')
    op.drop_index('uq_training_plan_published', table_name='training_plan', postgresql_where=sa.text("status = 'PUBLISHED'"))
    op.drop_table('training_plan')
    op.drop_index('ix_teaching_task_term_status', table_name='teaching_task')
    op.drop_table('teaching_task')
    op.drop_index('ix_teacher_campus_status', table_name='teacher')
    op.drop_table('teacher')
    op.drop_index('ix_student_class_major_year', table_name='student_class')
    op.drop_table('student_class')
    op.drop_index('ix_selection_window_term_status', table_name='selection_window')
    op.drop_table('selection_window')
    op.drop_index('uq_rule_set_published', table_name='rule_set', postgresql_where=sa.text("status = 'PUBLISHED'"))
    op.drop_table('rule_set')
    op.drop_index('ix_prompt_template_agent_status', table_name='prompt_template')
    op.drop_table('prompt_template')
    op.drop_index('ix_notification_recipient_status', table_name='notification')
    op.drop_table('notification')
    op.drop_index('ix_experiment_project_course_status', table_name='experiment_project')
    op.drop_table('experiment_project')
    op.drop_index('ix_agent_run_requester_status', table_name='agent_run')
    op.drop_table('agent_run')
    op.drop_index('ix_user_account_type_status', table_name='user_account')
    op.drop_table('user_account')
    op.drop_table('major')
    op.drop_table('experiment_course')
    op.drop_table('equipment_type')
    op.drop_table('campus')
    op.drop_table('academic_term')
    # ### end Alembic commands ###
